Replicas: 1
StorageClass: "rook-ceph-fs"
ExecutorDockerImage: "colonyos/kubeexecutor"
ColoniesServerHost: "server.colonyos.io"
ColoniesServerPort: 443
ColoniesTLS: true
ColoniesColonyName: "hpc"
ColoniesColonyPrvKey: ""
ColoniesExecutorName: "icekube"
ColoniesPrvKey: ""
AWSS3Endpoint: ""
AWSS3AccessKey: ""
AWSS3SecretKey: ""
AWSS3Region: ""
AWSS3Bucket: "hpc"
AWSS3TLS: "true"
AWSS3SkipVerify: "false"
ExecutorResourceLimit: true
ExecutorMemory: "6000Mi"
ExecutorCPU: "2000m"
ExecutorType: "ice-kubeexecutor"
ExecutorSWName: "colonyos/kubeexecutor"
ExecutorSWType: "kube-executor"
ExecutorSWVersion: "22.05.08"
ExecutorHWCPU: "25000m"
ExecutorHWModel: "ICE Connect EKS"
ExecutorHWNodes: "29"
ExecutorHWMem: "43600Mi"
ExecutorHWStorage: "10Gi"
ExecutorHWGPUCount: "4"
ExecutorHWGPUMem: "12GiB"
ExecutorHWGPUNodesCount: "4"
ExecutorHWGPUName: "nvidia_2080ti"
ExecutorLocationDesc: "ICE Datacenter, Sweden"
ExecutorLocationLong: "65.61204640586546"
ExecutorLocationLat: "22.132275667285477"
ExecutorFSDir: "/cfs"
ExecutorFSSize: "1Gi"
