apiVersion: apps/v1
kind: Deployment
metadata:
  name: kubeexecutor-deployment 
  labels:
    app: kubeexecutor 
spec:
  replicas: {{ (int .Values.Replicas) }} 
  selector:
    matchLabels:
      app: kubeexecutor
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0 
      maxSurge: 1
  template:
    metadata:
      annotations:
        timestamp: {{ now | quote }}
      labels:
        app: kubeexecutor
    spec:
      serviceAccountName: kubeexecutor-account 
      automountServiceAccountToken: true
      volumes:
        - name: cfs-volume 
          persistentVolumeClaim:
            claimName: {{ .Values.ExecutorK8sPVC }}
      containers:
      - name: kubeexecutor-container
        image: {{ .Values.ExecutorDockerImage | quote }}
        {{ if .Values.ExecutorResourceLimit }}
        resources:
          limits:
            memory: {{ .Values.ExecutorMemory | quote }}
          requests:
            cpu: {{ (.Values.ExecutorCPU | quote) }}
            memory: {{ .Values.ExecutorMemory | quote }}
        {{ end }}
        volumeMounts:
          - name: cfs-volume
            mountPath: {{ .Values.ExecutorFSDir }}
        env:
        - name: COLONIES_SERVER_HOST
          value: "{{ .Values.ColoniesServerHost }}"
        - name: COLONIES_SERVER_PORT
          value: "{{ .Values.ColoniesServerPort }}"
        - name: COLONIES_COLONY_ID
          value: "{{ .Values.ColoniesColonyID }}"
        - name: COLONIES_COLONY_PRVKEY
          value: "{{ .Values.ColoniesColonyPrvKey }}"
        - name: COLONIES_EXECUTOR_ID
          value: "{{ .Values.ColoniesExecutorID }}"
        - name: COLONIES_EXECUTOR_PRVKEY
          value: "{{ .Values.ColoniesExecutorPrvKey }}"
        - name: COLONIES_TLS
          value: "{{ .Values.ColoniesTLS }}"
        - name: COLONIES_VERBOSE
          value: "true"
        - name: AWS_S3_ENDPOINT
          value: "{{ .Values.AWSS3Endpoint }}"
        - name: AWS_S3_ACCESSKEY
          value: "{{ .Values.AWSS3AccessKey }}"
        - name: AWS_S3_SECRETKEY
          value: "{{ .Values.AWSS3SecretKey }}"
        - name: AWS_S3_REGION_KEY
          value: "{{ .Values.AWSS3Region }}"
        - name: AWS_S3_BUCKET
          value: "{{ .Values.AWSS3Bucket }}"
        - name: AWS_S3_TLS
          value: "{{ .Values.AWSS3TLS }}"
        - name: AWS_S3_SKIPVERIFY
          value: "{{ .Values.AWSS3SkipVerify }}"
        - name: EXECUTOR_TYPE
          value: "{{ .Values.ExecutorType }}"
        - name: EXECUTOR_SW_NAME
          value: "{{ .Values.ExecutorSWName }}"
        - name: EXECUTOR_SW_TYPE
          value: "{{ .Values.ExecutorSWType }}"
        - name: EXECUTOR_SW_VERSION
          value: "{{ .Values.ExecutorSWVersion }}"
        - name: EXECUTOR_HW_CPU
          value: "{{ .Values.ExecutorHWCPU }}"
        - name: EXECUTOR_HW_MODEL
          value: "{{ .Values.ExecutorHWModel }}"
        - name: EXECUTOR_HW_NODES
          value: "{{ .Values.ExecutorHWNodes }}"
        - name: EXECUTOR_HW_MEM
          value: "{{ .Values.ExecutorHWMem }}"
        - name: EXECUTOR_HW_STORAGE
          value: "{{ .Values.ExecutorHWStorage }}"
        - name: EXECUTOR_HW_GPU_COUNT
          value: "{{ .Values.ExecutorHWGPUCount }}"
        - name: EXECUTOR_HW_GPU_MEM
          value: "{{ .Values.ExecutorHWGPUMem }}"
        - name: EXECUTOR_HW_GPU_NODES_COUNT
          value: "{{ .Values.ExecutorHWGPUNodesCount }}"
        - name: EXECUTOR_HW_GPU_NAME
          value: "{{ .Values.ExecutorHWGPUName }}"
        - name: EXECUTOR_LOCATION_LONG
          value: "{{ .Values.ExecutorLocationLong }}"
        - name: EXECUTOR_LOCATION_LAT
          value: "{{ .Values.ExecutorLocationLat }}"
        - name: EXECUTOR_LOCATION_DESC
          value: "{{ .Values.ExecutorLocationDesc }}"
        - name: EXECUTOR_FS_DIR
          value: "{{ .Values.ExecutorFSDir }}"
        - name: EXECUTOR_K8S_NAME
          value: "{{ .Values.ExecutorK8sName }}"
        - name: EXECUTOR_K8S_NAMESPACE
          value: "{{ .Values.ExecutorK8sNamespace }}"
        - name: EXECUTOR_K8S_PVC
          value: "{{ .Values.ExecutorK8sPVC }}"
        - name: EXECUTOR_ADD_DEBUG_LOGS
          value: "false"
